services:
  backend:
    build:
      context: ./app1-backend
    container_name: app1-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
  frontend:
    build:
      context: ./app1-frontend-react
    container_name: app1-frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge
